-- DEPRECATED — do not run.
--
-- Lunch items were a separate seed and caused duplicate dishes alongside the Excel menu.
-- The canonical menu is ONLY supabase/seed-menu-from-old-system.sql (177 items from menu-old-system.xlsx).
--
-- To reset menu: run seed-menu-from-old-system.sql in Supabase SQL Editor.
-- Regenerate from Excel: python3 scripts/generate-menu-from-xlsx.py
